# Generated by Django 6.0.7 on 2026-08-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='E Five', max_length=80)),
                ('logo', models.ImageField(blank=True, upload_to='branding/')),
                ('announcement_en', models.CharField(default='Delivery across Algeria', max_length=160)),
                ('announcement_fr', models.CharField(blank=True, max_length=160)),
                ('announcement_ar', models.CharField(blank=True, max_length=160)),
                ('hero_title_en', models.CharField(default='Your hair. Your wave.', max_length=160)),
                ('hero_title_fr', models.CharField(blank=True, max_length=160)),
                ('hero_title_ar', models.CharField(blank=True, max_length=160)),
                ('hero_text_en', models.TextField(default='Texture, volume and natural movement. Discover effortless styling made for you.')),
                ('hero_text_fr', models.TextField(blank=True)),
                ('hero_text_ar', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='branding/')),
            ],
        ),
    ]
