# Generated by Django 6.0.7 on 2026-08-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZRExpressSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_base', models.URLField(default='https://api.zrexpress.app/api/v1')),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=255)),
                ('live_sync', models.BooleanField(default=False, help_text='Create a ZR Express parcel immediately after checkout')),
            ],
        ),
    ]
