# Generated by Django 6.0.7 on 2026-08-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_zrexpresssettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingPixelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable the saved tracking snippets across all storefront pages')),
                ('facebook_pixel_code', models.TextField(blank=True, help_text='Paste the complete Meta/Facebook Pixel JavaScript snippet')),
                ('tiktok_pixel_code', models.TextField(blank=True, help_text='Paste the complete TikTok Pixel JavaScript snippet')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
