# Generated by Django 6.0.7 on 2026-08-25 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('price', models.PositiveIntegerField(help_text='Price in DZD')),
                ('original_price', models.PositiveIntegerField(blank=True, null=True)),
                ('badge', models.CharField(blank=True, max_length=40)),
                ('name_en', models.CharField(max_length=150)),
                ('name_fr', models.CharField(blank=True, max_length=150)),
                ('name_ar', models.CharField(blank=True, max_length=150)),
                ('subtitle_en', models.CharField(max_length=200)),
                ('subtitle_fr', models.CharField(blank=True, max_length=200)),
                ('subtitle_ar', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField()),
                ('description_fr', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('benefits_en', models.TextField(help_text='One benefit per line')),
                ('benefits_fr', models.TextField(blank=True)),
                ('benefits_ar', models.TextField(blank=True)),
                ('usage_en', models.TextField()),
                ('usage_fr', models.TextField(blank=True)),
                ('usage_ar', models.TextField(blank=True)),
                ('main_image', models.ImageField(upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'name_en'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
