# Generated by Django 6.0.7 on 2026-08-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.PositiveSmallIntegerField(default=10, help_text='Centimetres'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.PositiveSmallIntegerField(default=10, help_text='Centimetres'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.2, help_text='Kilograms', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.PositiveSmallIntegerField(default=10, help_text='Centimetres'),
        ),
        migrations.AddField(
            model_name='product',
            name='zr_product_id',
            field=models.UUIDField(blank=True, help_text='Product ID from the ZR Express catalog', null=True),
        ),
    ]
